### ISSUE TITLE
Strange indentation when combining path with predicate-object list notation

### ISSUE THREAD

**Issue by wouterbeek** [Triply-Dev/YASGUI.YASQE-deprecated#100]
Indentation after using (a) compound path notation in combination with (b) predicate-object lists jumps to the last path separator.  I was expecting the indentation to be the same as for a path consisting of a single predicate term or variable.

Example:

```sparql
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
select * {
  ?s rdf:a/rdf:b/rdf:c ?o ;
                 *HERE*
```

**Comment by wouterbeek** [comment]
I now see that this may be a duplicate of #104

**Comment by LaurensRietveld** [comment]
This is fixed in the latest release (see https://github.com/TriplyDB/Yasgui and https://yasgui.triply.cc)
