### ISSUE TITLE
Auto-indentation does not take property path syntax into account

### ISSUE THREAD

**Issue by wouterbeek** [Triply-Dev/YASGUI.YASQE-deprecated#105]
After a semi-colon, YASQE tries to auto-indent to the starting position of the predicate term in the previous line.  When that predicate term is a predicate path expression, the auto-indentation seems to move to the beginning of the last term in that path expression (see query string below), but it should indent to the beginning of the first term in that path expression instead (in line with what the semi-colon abbreviates, i.e., only the subject term).

```sparql
prefix bag: <http://lod.geodan.nl/vocab/bag#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select ?wkt ?wktLabel {
  ?openbareRuimte bag:naamOpenbareRuimte "'t Spiker" ;
    bag:bijbehorendeWoonplaats/bag:naamWoonplaats ?woonplaats .
  ?nummeraanduiding bag:bijbehorendeOpenbareRuimte ?openbareRuimte ;
                    bag:huisnummer 24 .
  ?verblijfsobject bag:hoofdadres ?nummeraanduiding ;
                   bag:oppervlakte ?oppervlakte ;
                   bag:status ?verblijfsobjectStatus ;
                   bag:pandrelatering ?pand .
  ?pand bag:oorspronkelijkBouwjaar ?bouwjaar ;
        bag:geometriePand/geo:asWKT ?wkt ;
                         <HERE>
```

**Comment by LaurensRietveld** [comment]
This is fixed in the latest version (see https://github.com/TriplyDB/Yasgui and https://yasgui.triply.cc)
