### ISSUE TITLE
Prefix declarations are not added for datatype IRIs

### ISSUE THREAD

**Issue by wouterbeek** [Triply-Dev/YASGUI.YASQE-deprecated#109]
(1) Subject IRIs, (2) predicate IRIs, (3) object IRIs, (4) graph IRIs, and (5) datatype IRIs are all abbreviated in the same way and by using the same set of prefix declarations.  Currently prefix declarations are *automatically* added for (1-4) but not for (5).

Reproducible case:

```sparql
select * { ?s ?p "a"^^xsd:string }
```

Notice that the prefix declaration for `xsd` was not added.

**Comment by LaurensRietveld** [comment]
This is fixed in the latest version (see https://github.com/TriplyDB/Yasgui and https://yasgui.triply.cc)
