### ISSUE TITLE
Some features do not work in property paths

### ISSUE THREAD

**Issue by wouterbeek** [Triply-Dev/YASGUI.YASQE-deprecated#110]
Some YASQE features do not work in property paths.  For instance, if point is at the end of the following string, automatic prefix declaration and auto-complete do not work:

```
?s geo:hasGeometry/xsd:
```

**Comment by LaurensRietveld** [comment]
These features (both auto-prefix declaration and auto-complete) now work in property-paths in the latest version  (see https://github.com/TriplyDB/Yasgui and https://yasgui.triply.cc)
