### ISSUE TITLE
Consider internationalization

### ISSUE THREAD

**Issue by jindrichmynarz** [Triply-Dev/YASGUI.YASQE-deprecated#111]
I would be useful if the strings in English that are displayed to users were extracted to allow internationalization. Currently, these strings are scattered throughout the code, such as in the [autocomplete](https://github.com/OpenTriply/YASGUI.YASQE/blob/gh-pages/src/autocompleters/autocompleterBase.js#L232-L234) or in [the interface](https://github.com/OpenTriply/YASGUI.YASQE/blob/gh-pages/src/main.js#L552).

**Comment by LaurensRietveld** [comment]
Seems like a reasonable thing to do. The thing that's holding me back is the integration of 3rd party UI libs (e.g. datatables, Google chart, the pivot table plugin,and perhaps other in the future). These may or may not support internationalization..

**Comment by jindrichmynarz** [comment]
These are YASR plugins, right? In YASQE, internationalization would be related mostly to itself, so it may be simpler to achieve.

YASR already nicely exposes ways to localize plugins, such as `YASR.plugins.table.defaults.datatable.language` for DataTables.
