### ISSUE TITLE
The GeoSPARQL property for default geometries is missing

### ISSUE THREAD

**Issue by wouterbeek** [Triply-Dev/YASGUI.YASQE-deprecated#122]
Property `geo:hasDefaultGeometry` is currently not available in autocompletion (its superproperty `geo:hasGeometry` is available).

**Comment by LaurensRietveld** [comment]
Closing, as this is more of an issue with LOV (https://lov.linkeddata.es/dataset/lov/) than it is with Yasgui. All Yasgui does is use the autocomplete API provided by LOV. Apparently the geo vocabulary on LOV is incomplete/incorrect
