### ISSUE TITLE
Load autocomplete LOV over appropriate protocol

### ISSUE THREAD

**Issue by reinvantveer** [Triply-Dev/YASGUI.YASQE-deprecated#123]
For https://data.pdok.nl:
```
jquery-3.1.1.min.js?version=:4 Mixed Content: The page at 'https://data.pdok.nl/sparql' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://lov.okfn.org/dataset/lov/api/v2/autocomplete/terms?q=brk&page=1&type=class'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by LaurensRietveld** [comment]
I think this was an outdated YASGUI version (this was fixed recently already). Could you check again?

**Comment by wouterbeek** [comment]
@reinvantveer Can you check this?  Would be nice to close this issue if it's already fixed.

**Comment by LaurensRietveld** [comment]
This was resolved over a year ago by https://github.com/OpenTriply/YASGUI.YASQE/blob/gh-pages/src/autocompleters/utils.js#L52 . It seems pdok indeed uses an outdated version at location `/sparql`. The `/yasgui` page seems to be up-to-date

**Comment by reinvantveer** [comment]
OK!
