### ISSUE TITLE
Error in strict mode

### ISSUE THREAD

**Issue by namedgraph** [Triply-Dev/YASGUI.YASQE-deprecated#13]
Hey, I'm using YASQE with `application/xhtml+xml` media type (which enforces strict mode in browsers) and I get this JavaScript error:
`SyntaxError: An invalid or illegal string was specified
http://localhost:8080/graphity-client/static/js/yasqe.js
Line 24133`
I think this could be refactored in a XHTML-compliant way. Better to avoid `.innerHTML`, but this entity reference could also be a problem.

**Comment by LaurensRietveld** [comment]
Ah, I'll take a look. Could you give more information though? I was not able to reproduce this issue (tried changing the doctype to xhtml, without result). 
Which browser did you use? If you have a small working test-case, that would be even better
