### ISSUE TITLE
Username/password

### ISSUE THREAD

**Issue by art-tom** [Triply-Dev/YASGUI.YASQE-deprecated#134]
Hello,

I try to execute my query with authentification but I doesn't work.
I try with this issue and no result https://github.com/OpenTriply/YASGUI.YASQE/issues/94

My error in console is No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 401.

Please help me
Thank in advance,

**Comment by LaurensRietveld** [comment]
To check whether this is a bug (this is a issue tracker after all), could you first create a minimum working example that reproduces this issue? 
E.g., a js snippet that can successfully issue a plain ajax request against your endpoint using authentication, and a js snippet where yasqe fails to issue such a request.

Asking that for this ticket specifically, as this is probably not a yasqe issue, but a misconfigured sparql endpoint. 
Some pointers, google for authentication and CORS (that combination specifically), and follow links that describe which headers the server should return to properly allow cross-origina javascript scripts
