### ISSUE TITLE
Forward slash not allowed in query editor

### ISSUE THREAD

**Issue by amalic** [Triply-Dev/YASGUI.YASQE-deprecated#138]
I have to escape forward slashes, I don't understand why.

E.g. this is not a valid query in YASQE
```SQL
PREFIX : <http://example.com/>
SELECT ?thing WHERE {
  ?thing a :category/subcategory/thing
}
```

Instead I have to escape forward slashes:
```SQL
PREFIX : <http://example.com/>
SELECT ?thing WHERE {
  ?thing a :category\/subcategory\/thing
}
```

I could not find a rationale for this.

**Comment by wouterbeek** [comment]
@amalic Can you double-check this?  AFAIK forward slashes are not allowed in Turtle/SPARQL local names.

**Comment by LaurensRietveld** [comment]
Closing, as indeed this is not allowed
