### ISSUE TITLE
variable list has invalid values

### ISSUE THREAD

**Issue by trapperkeeper** [Triply-Dev/YASGUI.YASQE-deprecated#145]
yasqe.getVariablesFromQuery() returns values that used to be in the query but are no longer there (e.g. as you edit, new variables are added to the list, but their old value is never removed). Is there any way to clear these out?

**Comment by trapperkeeper** [comment]
I forgot to include that I am presently using this distribution:

//cdn.jsdelivr.net/npm/yasgui-yasqe@2.11.22/dist/yasqe.bundled.min.js

**Comment by trapperkeeper** [comment]
Just FYI, for others that might encounter this issue, I am currently just doing a yasqe.getValue() to get the query and then using this regex to get the current variables:

/\?\w+/g

**Comment by LaurensRietveld** [comment]
I could not reproduce this in the latest version (see https://yasgui.triply.cc and https://github.com/TriplyDB/Yasgui)
It it's still a problem, please open an issue here: https://github.com/TriplyDB/Yasgui
