### ISSUE TITLE
used prefixes are not correctly updated in prefixes array 

### ISSUE THREAD

**Issue by JJ-Author** [Triply-Dev/YASGUI.YASQE-deprecated#150]
if you use prefixes in yasqe and then decide to rename it (bug seems to only occur for the last prefix entry) the getPrefixesFromQuery() method will return both the old prefix name(s) but also the new prefix name. as a result in yasr still the old prefix will be used to prettify IRIs. I've made a test page for you here in order to reproduce it: https://databus.dbpedia.org/yasgui/yasgui_jan.html 
just replace `rdfs` by `rdfsd` and you will get `{"rdf":"http://www.w3.org/1999/02/22-rdf-syntax-ns#","rdfs":"http://www.w3.org/2000/01/rdf-schema#","rdfsd":"http://www.w3.org/2000/01/rdf-schema#"}`

Note if you change now the first prefix both prefixes get updated correctly. probably some index var problem

**Comment by LaurensRietveld** [comment]
Thanks, this is fixed now in the latest version  (see https://github.com/TriplyDB/Yasgui and https://yasgui.triply.cc)
