### ISSUE TITLE
Autocompleters do not work in fullscreen mode

### ISSUE THREAD

**Issue by mistermboy** [Triply-Dev/YASGUI.YASQE-deprecated#153]
Why the autocompleters do not work in fullscreen mode?

**Comment by bjonnh** [comment]
Last time I had that it was an issue with the z-index of tooltips vs the window. I thought https://github.com/TriplyDB/YASGUI.YASQE/commit/9e36365fae3f68799d9473cf642f2ed317c8895a would have solved that.

**Comment by mistermboy** [comment]
Fixed with #155
