### ISSUE TITLE
Make gists for usage examples

### ISSUE THREAD

**Issue by LaurensRietveld** [Triply-Dev/YASGUI.YASQE-deprecated#22]
Connected to #20.
Examples:
- change 'onclick behaviour

**Comment by LaurensRietveld** [comment]
https://github.com/blairvanderhoof/gist-embed looks interesting. use that one.

And, annotate the gists with #yasqe and/or #yasr, so we can dynamically search/include these on our documents page by searching for username (Laurensrietveld) and these tag names. Gists don't support proper tags yet though, so put these tag names in title

**Comment by LaurensRietveld** [comment]
havent found a way to use search api for gists. Instead, just fetch the gists connected to my account, and filter based on description tags (https://api.github.com/users/LaurensRietveld/gists)

**Comment by LaurensRietveld** [comment]
Perhaps, alternatively to the gist-embed library, use the bl.ocks service. See http://bl.ocks.org/LaurensRietveld/7d8beca5dbeb6b909b6f and http://bl.ocks.org/LaurensRietveld/raw/7d8beca5dbeb6b909b6f

This does not mess up our interface with code examples, and would make this addition very lightweight.

E.h., link to the /raw/ bl.ocks.org page, link to the regular github page (so people can leave comments and see the history+code), and on the YASQE page show the title, and fetch the README.md text (if there is any). https://api.github.com/gists/7d8beca5dbeb6b909b6f

**Comment by jneubert** [comment]
This sounds really interesting - looking forward to it! Cheers, Joachim
