### ISSUE TITLE
acceptHeaderGraph apparently not working

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASQE-deprecated#27]
I've tried a construct query with the default value of acceptHeaderGraph, and also setting explicitely

```
var yasqe = YASQE(document.getElementById("yasqe"), {
  sparql: {
    showQueryButton: true,
    acceptHeaderGraph: "text/turtle,*/*;q=0.9"
  },
  consumeShareLink: consumeUrl
});
```

but it looks like "application/sparql-results+json" is requested (and my endpoint choses to return rdf/xml).

**Comment by LaurensRietveld** [comment]
On what YASQE version did you try this? (you can get the version by accessing YASQE.version in js)

**Comment by jneubert** [comment]
I used the current version from the cdn as 1.5.2, and verified that it has loaded from http://cdnjs.cloudflare.com/ajax/libs/yasqe/1.5.2/yasqe.bundled.min.js. Yet, YASQE.version shows 1.5.1. My code is at http://zbw.eu/beta/sparql-gui.

**Comment by LaurensRietveld** [comment]
Ah, good to know. My guess is the accept header issue is resolved, but an
invalid version is somehow pushed to cdnjs. I'll check it out tonight

gr Laurens

**Comment by LaurensRietveld** [comment]
Could you check again with the new version? The 1.5.3 version should be available on cdnjs within 15 minutes

**Comment by LaurensRietveld** [comment]
hmm, issues with the cdnjs autoupdate functionality. If the 1.5.3 version is still not available via cdn tomorrow, you might better try it by downloading the files from github

**Comment by jneubert** [comment]
It work now perfectly! Thanks a lot - Joachim

**Comment by LaurensRietveld** [comment]
ok, excellent ;)
