### ISSUE TITLE
'gulp' results in "Cannot find module './lib/notifiers/notify-send'"

### ISSUE THREAD

**Issue by esjewett** [Triply-Dev/YASGUI.YASQE-deprecated#3]
Did a clean clone and it looks like a dependency of the gulp-notify module has gone haywire. For the moment, I'm just removing gulp-notify and all notifications from the Gulpfile.

**Comment by LaurensRietveld** [comment]
Ah, I think I pushed in the middle of a refactoring process. No problem, thats fine, I'll make sure to solve this in a merge.

**Comment by LaurensRietveld** [comment]
will leave this out of gulp for now (already done in #2 ), as this gulp module apparently does not work well with all operating systems. If needed, exchange this with gutils.log in the future
