### ISSUE TITLE
Just show the results ...

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASQE-deprecated#35]
Hi Laurens, 

I want to show query results to end users. For this purpose, I want (optionally, by url arg) to hide the query and the output selector. This should be easy (document.getElementById(yasqe).style.display = 'none' and yasr.drawOutputSelector: false), but due to my poor javascript knowledge I haven't yet figured out how to apply this syntactically. If you still are planing to provide gists for different usage scenarios, this could be a nice use case :-)

Cheers, Joachim

**Comment by LaurensRietveld** [comment]
Jup, I can get together a simple gist for that. Will take a look over the weekend. I'll try to combine it with #22, so we have a set of gists on the main page

**Comment by LaurensRietveld** [comment]
Hi Joachim,

Here is a simple example on how to do this: https://gist.github.com/LaurensRietveld/a65749b9fbe9e6b1dcd5

Good luck, 
Laurens

ps. did not add it to the running list of gists yet. Still thinking on what type of gists to include in the documentation as illustrative examples
