### ISSUE TITLE
Cannot reinitialise DataTable

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASQE-deprecated#39]
When I re-execute a query, I get an alert:

DataTables warning: table id=DataTables_Table_0 - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

Perhaps best thing would be to clear the table at start of page load/execution of yasqe. (Currently, without special precautions, the results from the previous query are displayed even if an error occured, .e.g. another query referenced by queryRef could not be loaded).

**Comment by LaurensRietveld** [comment]
Ah, I get the same error. What version are you using? I think some
refactoring done for version 2.x.x caused this, so if its urgent, you can
use the 1.x.x versions.
I'll take a look at the issue later tomorrow

**Comment by jneubert** [comment]
Ok, I used 2.0 - for now I will switch back to 1.x. Thanks, Joachim

**Comment by LaurensRietveld** [comment]
Hi Joachim,
I've fixed this issue in the YASR repo (see https://github.com/YASGUI/YASR/issues/13)

Thanks for the report, as usual ;)

gr Laurens
