### ISSUE TITLE
Strange error for long running query

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASQE-deprecated#43]
Don't know how relevant this is, but just wanted to report:
I've a query which takes about 90 seconds. When I ran it on http://yasgui.laurensrietveld.nl/, the first time I got an 504 error. When I tried to repeat in Firebug, I got a response "exception: Lexical error at line 21, column 9.  Encountered: " " (32), after : "VALUES"" by YasguiService, but only after the result from the endpoint has been returned (with obviously correct content).

http://goo.gl/a1we1K

(the URL shortener didn't work for the rather lengthy query).

**Comment by LaurensRietveld** [comment]
Hi Joachim,

Thanks for the report. I won't touch the current YASGUI version for this,
but will take it into account for the new YASGUI version ;)

gr Laurens
