### ISSUE TITLE
Downloading of CSV not working in firefox

### ISSUE THREAD

**Issue by LaurensRietveld** [Triply-Dev/YASGUI.YASQE-deprecated#45]

**Comment by jneubert** [comment]
Maybe somehow related: With YASR 2.4.1, I'm not able to download SVG graphics (the button stays grey), in Chrome as well as in FF.

**Comment by LaurensRietveld** [comment]
Oops, posted as YASQE bug instead of YASR bug. Closed here, and continuing in YASR issue ;) (https://github.com/YASGUI/YASR/issues/39). 
And thanks Joachim, will take that into account as well
