### ISSUE TITLE
Editor marks literals containing codepoint escape sequences as invalid

### ISSUE THREAD

**Issue by dwvisser** [Triply-Dev/YASGUI.YASQE-deprecated#49]
SPARQL allows for Unicode codepoint escape sequences anywhere (http://www.w3.org/TR/sparql11-query/#grammar). Could YASQE at least allow them inside quoted literals.without marking the code as invalid? See, e.g., https://openrdf.atlassian.net/browse/SES-2172, for examples of valid SPARQL/Update getting highlighted as invalid in YASQE.

**Comment by LaurensRietveld** [comment]
Too bad that SPARQL allows for these escape sequences, but did not include them in the official grammar.
But I agree that YASQE should have at least a basic support for this. I.e. support in literals, but preferably also prefixes, namespaces and URIs
I'll see what I can do

**Comment by LaurensRietveld** [comment]
The latest yasqe version now properly validates literals when these escape sequences are there. 
This already works for URIs as well. The only occasion where it does not work is prefixes and prefix localnames. I'd like to avoid getting into that though: I'd need to make bigger changes to the grammar, and I'd like to deviate as little as possible from the official spec

Could you check on http://yasqe.yasgui.org whether the new version is ok?

**Comment by dwvisser** [comment]
Verified new version fixes my specific issue (\uxxxx in literals). Noticed it doesn't handle \Uxxxxxxxx possibility. That's OK for my purposes for the time being.

**Comment by LaurensRietveld** [comment]
Ah, indeed. The \Uxxxxxx is now handled properly as well.

**Comment by dwvisser** [comment]
I see the commit adding U as a possibility. It doesn't seem to work at http://yasqe.yasgui.org/, though. Has the site been updated?

Also, it would be good to ensure that the large \U variant limits valid values to the range U+0 to U+10FFFF, as specified at http://www.w3.org/TR/sparql11-query/#grammar.

BTW, I am very grateful for you addressing this. :-)

**Comment by LaurensRietveld** [comment]
The site should be up-to-date. Perhaps a js caching issue? 

About excluding this range: integrating this in the tokenizer is tricky, as it'd require quite a complex regex.
Not that keen on doing that, as I'd like to keep the delta small w.r.t. the original spec, and I'm more keen on avoiding false negatives than on avoiding false positives.
Any comment on this?

**Comment by dwvisser** [comment]
I'd be OK with that. As a suggestion only, I've created a pull request that AFAIK, does the filtering to only U+0 to U+10FFFF. Let me know what you think?

**Comment by LaurensRietveld** [comment]
Ah, that's a smaller delta than I expected ;). Thanks, I merged the pull request and re-build the most recent version

**Comment by dwvisser** [comment]
OK. When you have time, could you do a pull request to get this incorporated into the Sesame Workbench 2.7.x branch? You can reference issue SES-2172.
