### ISSUE TITLE
Show a busy indicator on the visible part of the screen

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASQE-deprecated#52]
Because I have lengthy queries to edit, I use "viewportMargin: Infinity". Currently, when I edit such a query, I can execute it by ctrl-enter without scrolling back to the top of the yasqe window, but I get no indication when execution is finished - because the busy indicator spins on the upper right corner of window.

Would be nice to have another spinning wheel in the center of the visible portion of the yasqe window.

**Comment by LaurensRietveld** [comment]
This is tricky with css alone. We need some js magic to switch the buttons from absolute and fixed positioning, and make sure the right/top offsets are properly adjusted on scroll and dom modifications.
Tricky do properly for all browsers, and something I'd like to avoid to be honest ;). 
Does the solution in #53 solve this inconvenience enough? If so, then I suggest leaving this ticket be

**Comment by jneubert** [comment]
Ok, I wasn't aware that this might be complicated. #53 solves it quite fine. Perhaps, some additional blurring or darkening of the code window could indicate that something is happening (and the code cannot be edited for now).

**Comment by LaurensRietveld** [comment]
I've added an option to enable 'backdrop' on query execution: see the docs (http://yasqe.yasgui.org/doc , 'backdrop' option) on how to enable this.
Good luck! ;)

**Comment by jneubert** [comment]
Great - works like a charm. Thanks!
