### ISSUE TITLE
Jump to result section when a query has finished

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASQE-deprecated#53]
Related to #52 - is it possible to jump to the yasr results, when a yasqe query has finished execution?

**Comment by LaurensRietveld** [comment]
This is something more appropriate for the http://github.com/YASGUI/YASGUI library 
To implement this yourself to the combination of YASQE and YASR, I suggest you use the `scrollIntoView` DOM function:
go to the `complete` callback function of YASQE (the same function where you set the YASR results),
and add something like `document.getElementById('<dom-id-of-yasr').scrollIntoView()`

**Comment by jneubert** [comment]
Yes, that works fine. Since I had to fiddle with the syntax, her my code:

``` javascript
yasqe.options.sparql.callbacks.complete = function() {
  document.getElementById('yasr').scrollIntoView()
  window.yasr.setResponse.apply(this, arguments);
}
```

Thanks!
