### ISSUE TITLE
Support BASE keyword in SPARQL queries

### ISSUE THREAD

**Issue by dwvisser** [Triply-Dev/YASGUI.YASQE-deprecated#54]
Reported in Sesame issue tracker [SES-2184](https://openrdf.atlassian.net/browse/SES-2184), BASE keyword usage described at http://www.w3.org/TR/sparql11-query/#relIRIs:

just allow the keyword BASE in yasqe editor.
The following works fine, but Yasqe doesn't agree (red warning).

```
BASE <http://myRoot/>
select ?x where
{ <myPackage1/myFinal> a ?x } 
```

**Comment by LaurensRietveld** [comment]
@dwvisser : Strange,  I cannot reproduce this. Both on yasqe.yasgui.org, as well my sesame installation, this query doesnt show any error
When did you get this error: while typing it, or while e.g. copy pasting it? (I'm thinking there might be a situation where the validation state is not properly refreshed and up-to-date with the latest query)

**Comment by dwvisser** [comment]
My apologies. I passed this on without attempting to reproduce it. I'll recommend to the creator of the Sesame issue to answer your questions here.

**Comment by pirelaurent** [comment]
(i don't know how to attach a file with a spash screen) so i describe : 
In editor, the line with BASE http://myroot has a red warning on the left and a popup with :
This line is invalid.
Expected: PREFIX, $, CONSTRUCT, DESCRIBE, ASK, INSERT, DELETE, SELECT, LOAD, CLEAR, DROP, ADD, MOVE, COPY, CREATE, WITH
HTH

**Comment by pirelaurent** [comment]
I had investigated a bit more ( after ineffective cache clean) and find : 
YASQE allows a mix of PREFIX and BASE  *only *if BASE is the very first one : 

case 1: (which was mine) : 
PREFIX rdfs: http://www.w3.org/2000/01/rdf-schema#
BASE http://S_/Interoperabilite/2014/Composants_techniques/   !!! RED ALERT!!!

case 2 (alone): OK
BASE http://S_/Interoperabilite/2014/Composants_techniques/ 

Case 3: OK
BASE http://S_/Interoperabilite/2014/Composants_techniques/
PREFIX rdfs: http://www.w3.org/2000/01/rdf-schema# 

(SPARQL doesn't take care of order)

**Comment by LaurensRietveld** [comment]
Thanks, that helps a lot. This seems to be a bug I introduced 2 years ago, when I extended the sparql 1.0 tokenizer to 1.1.  (the PREFIX + BASE order is invalid according to sparql 1.0 grammar)
I'll make sure to change the tokenizer and grammar

**Comment by dwvisser** [comment]
@LaurensRietveld, when it's ready, could you create a pull request to merge this change into Sesame Workbench ([SES-2184](https://openrdf.atlassian.net/browse/SES-2184)) like you did with the Unicode escape codes change before?

**Comment by LaurensRietveld** [comment]
of course, will do!

**Comment by LaurensRietveld** [comment]
the new version of yasqe (already live at yasqe.yasgui.org) now uses the up-to-date sparql prologue definition.
