### ISSUE TITLE
Multiline triple quotes return a parse error when in fact they are valid sparql

### ISSUE THREAD

**Issue by nikolavp** [Triply-Dev/YASGUI.YASQE-deprecated#58]
Here is an example that is parsed without problems(i.e. there are not errors)

```
SELECT * WHERE {
    ?sub ?pred '''test'''
} LIMIT 10
```

but this one gives an error when in fact it is valid sparql syntax 

```
SELECT * WHERE {
    ?sub ?pred '''
test'''
} LIMIT 10
```

**Comment by LaurensRietveld** [comment]
Thanks, fixed in the new version.
Background on this bug: codemirror incrementally parses each line separately. The tokenizer now keeps track of the state (i.e. is a line preceded by a line with opening triple-quotes),

**Comment by nikolavp** [comment]
That was fast, thanks ;)
