### ISSUE TITLE
Feature request: Complete namespaces from <sesame_url>/repositories/repo/namespaces

### ISSUE THREAD

**Issue by alanruttenberg** [Triply-Dev/YASGUI.YASQE-deprecated#60]
See http://rdf4j.org/sesame/2.7/docs/system.docbook?view#chapter-http-protocol

Would be very nice to have. 

<sesame_url>/repositories/repo is the sparql endpoint

**Comment by LaurensRietveld** [comment]
I'd prefer not to add a triple-store specific dependency to YASQE. But the current autocompletion system should be very extendeable to accomodate your request. 

All you would need to do is use the current prefix autocompleter (https://github.com/YASGUI/YASQE/blob/gh-pages/src/autocompleters/prefixes.js) and change the get function to fetch the sesame ones.
An example of how to extend an existing autocompleter is found in this gist: http://bl.ocks.org/LaurensRietveld/3549c02f5727346ae89c
(this gist if quite lengthy though. In your case you'd only need to change the get function)

Let me know if this is what you were looking for
