### ISSUE TITLE
Suggestion: Use rdf:labels in query results

### ISSUE THREAD

**Issue by alanruttenberg** [Triply-Dev/YASGUI.YASQE-deprecated#61]
It would be nice if there was a switch that enabled displaying labels (with the URIs as href) in query results. In the ontologies I use URIs are opaque. If there isn't a label for a term then my suggestion would be to fall back to the localname of the URI.

Since this is a use interface thing, it would suffice, I think, to, to fetch the labels on display of the page. If there is concern about time then the first display could be of the URIs, with async updating of the elements once the labels arrived.

**Comment by jneubert** [comment]
Hi Alan,

if you have access to the labels within the same result, you can use YASRs "mergeLabelsWithUris" option (see http://yasr.yasgui.org/doc/) - works great.

If the labels had to be fetched separately, the requirement has similarities to https://github.com/YASGUI/YASR/issues/16.

Cheers, Joachim

**Comment by jneubert** [comment]
And perhaps you could just use the fetchTitlesFromPreflabel YASR option, as it is.

**Comment by LaurensRietveld** [comment]
Thanks both for the suggestion. Using dereferenceable URIs is indeed a nice one. I've added it as part of this feature: https://github.com/YASGUI/YASR/issues/67

**Comment by alanruttenberg** [comment]
@jneubert thanks for the suggestion regarding mergeLabelsWithUris - I'll see about trying that, though see below re: version.

Preflabel doesn't work for me - many URIs are private - I work with patient data.
To be clear, the labels are in the repo - I don't need/want to dereference the URIs, just to get them from the same endpoint that the URIs come from.

I suppose another way to do this would be to transform the SPARQL query on the way out, adding 
optional {?var rdfs:label ?varLabel} for each ?var in the select and adding the labels to the request - that would work at least when there were not aggregates in the select. For aggregates it is more complicated as non-aggregate variables have to also be added to the "group by" and I'm not sure whether that would mess the query.
Are there hooks that would let me try this?

Finally, the tool I am using (graphdb) is using version 1.3.1. Are there notes that would give some hints about what I have to modify to use the latest version?

**Comment by LaurensRietveld** [comment]
Hi @alanruttenberg 

Interesting, didn't know yasgui was integrated in graphdb already.
It should be possible to set your own custom hook supporting this (and if not I can easily make one). 
I'll take a look (also at the graphdb yasgui version) later this week, and let you know

**Comment by wouterbeek** [comment]
This seems to be a feature request for YASR?  I'm closing this now under the assumption that work on this issue continues in YASR issue https://github.com/OpenTriply/YASGUI.YASQE/issues/61

(Feel free to re-open if I misunderstood the issue.)
