### ISSUE TITLE
feature request: let prefixes be foldable

### ISSUE THREAD

**Issue by alanruttenberg** [Triply-Dev/YASGUI.YASQE-deprecated#62]
I rarely want to see them. If they could be folded by default that would be sweet.

**Comment by LaurensRietveld** [comment]
Hi alan,

this is implemented in the newest version. I've turned folding by default off for now, but that might change in the future (I'll ask around whether auto-fold on page load is something that users would like to see)
To turn auto-fold on, set `YASQE.defaults.collapsePrefixesOnLoad = true`

**Comment by alanruttenberg** [comment]
Thanks so much!
I have a question: I'm currently using the http://cdn.jsdelivr.net/yasgui/1.1.5/yasgui.min.js
What do I need to do to use the updated YASQE? Is there a makefile of some sort, or is there a way to run out of the repo?
