### ISSUE TITLE
feature request - highlight instance of same var when over one of them

### ISSUE THREAD

**Issue by alanruttenberg** [Triply-Dev/YASGUI.YASQE-deprecated#65]
Sometimes queries are long and variable names are similar and it is easy to make a mistake. However if you can at a glance see all the places you used the same variable it becomes much easier to detect such mistakes. 

I'd suggest a very pale background color on the other instances of the variable use.

**Comment by LaurensRietveld** [comment]
I like it, will include it in a few days

**Comment by LaurensRietveld** [comment]
added it anyway. new version of yasgui (online in a few minutes) will have the highlighting feature as well

**Comment by alanruttenberg** [comment]
Cool :)
Minor glitch - vars with same initial substring get hilited too

![screen shot 2015-05-08 at 4 13 35 pm](https://cloud.githubusercontent.com/assets/241934/7544728/c18f16a6-f59d-11e4-9919-383c914a0302.png)

**Comment by LaurensRietveld** [comment]
Oops, I'll take a look

**Comment by alanruttenberg** [comment]
This looks good: 
.matchingVar {background-color:#FFCCCC!important; border-radius: 6px;transition: background 1s linear;}

Less likely to flash as you casually move the mouse over text.

**Comment by LaurensRietveld** [comment]
I've fixed the variable string matching, and modified to css much like your example
