### ISSUE TITLE
suggestion: mark warning for prefixes not yet defined

### ISSUE THREAD

**Issue by alanruttenberg** [Triply-Dev/YASGUI.YASQE-deprecated#66]
Generally you get this error 1 step later when you submit the query, but it could be detected earlier.

**Comment by LaurensRietveld** [comment]
I'll see whether this is possible without too much of a performance hit

**Comment by LaurensRietveld** [comment]
a bit overdue, but now added to the latest yasqe version (see yasqe.yasgui.org for demo)

**Comment by LaurensRietveld** [comment]
forgot to add one comment: because of the incremental tokenization, the current implementation is not bullet-proof. False-negatives are possible (e.g. when commenting or removing a prefix). False-positives aren't though. 
Guess this should suffice though
