### ISSUE TITLE
Invalid warnings for predicate-object list when one of the objects is a blank node containing a predicate path

### ISSUE THREAD

**Issue by dwvisser** [Triply-Dev/YASGUI.YASQE-deprecated#69]
Here's the simplest query I find that reproduces the issue:

``` sql
PREFIX ex: <http://example.org/>

SELECT * WHERE {
  ?a ex:foo ?b ;
     ex:bar [ ex:baz/ex:buz ?c ].
}
```

The issue seems to be occur whenever a graph pattern contains:
1. a predicate-object list, where
2. the second (or later) object is a blank node, and
3. the blank node contains a predicate path.

This bug is also filed at https://openrdf.atlassian.net/browse/SES-2255

**Comment by LaurensRietveld** [comment]
Are you sure this is valid SPARQL 1.1? 
If I look at the spec, I see that the BlankNodePropertyList ([99]) lists verbs (i.e. IRI/var) as possible property values, but not property paths

**Comment by dwvisser** [comment]
I think that [TriplesSameSubjectPath](http://www.w3.org/TR/sparql11-query/#rTriplesSameSubjectPath) allows this to be valid SPARQL, using
- [VarOrTerm](http://www.w3.org/TR/sparql11-query/#rVarOrTerm) [PropertyListPathNotEmpty](http://www.w3.org/TR/sparql11-query/#rPropertyListPathNotEmpty)
- PropertyListPathNotEmpty --> [VerbSimple](http://www.w3.org/TR/sparql11-query/#rVerbSimple) [ObjectListPath](http://www.w3.org/TR/sparql11-query/#rObjectListPath)
- ObjectListPath -> [ObjectPath](http://www.w3.org/TR/sparql11-query/#rObjectPath)
- ObjectPath -> [GraphNodePath](http://www.w3.org/TR/sparql11-query/#rGraphNodePath)
- GraphNodePath -> [TriplesNodePath](http://www.w3.org/TR/sparql11-query/#rTriplesNodePath)
- TriplesNodePath -> [BlankNodePropertyListPath](http://www.w3.org/TR/sparql11-query/#rBlankNodePropertyListPath)

which leads into property paths.

**Comment by dwvisser** [comment]
Wait. I see your point. The construction I gave in my the second bullet of my last comment is only valid for the first predicate-object pair, not the subsequent ones, which is precisely what is manifesting here.

**Comment by abrokenjester** [comment]
Hm. I think this may be an error in the SPARQL grammar. It certainly seems arbitrary to allow property paths in a blank node object for the _first_ object after a subject/predicate pairing, but not for any subsequent ones. It doesn't look like this was done by design, to me. Agreed though that YASQE implements what the current spec prescribes.

**Comment by LaurensRietveld** [comment]
If you have an EBNF for queries that sesame supports, it should be pretty straightforward to generate a JS grammar based on that. (see https://github.com/YASGUI/YASQE/tree/gh-pages/lib/grammar)

**Comment by dwvisser** [comment]
Thank you. I have tested and Sesame _does_ successfully run the query, despite it not being valid according to the official SPARQL 1.1 grammar. I have posted the result on the Sesame issue tracker.
