### ISSUE TITLE
Make query params configurable for select/update

### ISSUE THREAD

**Issue by LaurensRietveld** [Triply-Dev/YASGUI.YASQE-deprecated#74]
Right now the query type (select or update) automatically changes the query parameter that is send via ajax. For `SELECT` queries `query=` is used, where `UPDATE` queries use `update=`. 
Allow the user to configure this

**Comment by jiemakel** [comment]
YASQE (also on yasgui.org) is currently broken at least for me, probably as a result of work on this. utils.getString isn't defined/doesn't work, resulting in the form submitting the query under the parameter `undefined`. Downgrading my YASQE to 2.6.3 fixed the problem for me.

**Comment by LaurensRietveld** [comment]
ouch, this commit shouldnt have been there. thanks for the warning. (fixed in newest YASQE/YASGUI versions)
