### ISSUE TITLE
Support autocompleting by querying own endpoint

### ISSUE THREAD

**Issue by LaurensRietveld** [Triply-Dev/YASGUI.YASQE-deprecated#81]
YASQE uses the lov api by default because some endpoints are too slow in answering the autocompletion SPARQL queries. 
There is gist (https://gist.github.com/LaurensRietveld/3549c02f5727346ae89c) that shows how to use SPARQL queries for autocompletion, but guess it is better to integrate this in YASQE directly as well (still with lov as default though)

**Comment by wouterbeek** [comment]
For my understanding: you would (1) offer a function for SPARQL-based auto-completion and (2) would add a configuration option where the function that retrieves auto-completion results from LOV could be overrules by the function from (1)?

**Comment by LaurensRietveld** [comment]
jup, that would be it. The yasgui.org instance would use lov by default, but if somebody wants to run YASQE locally on an endpoint that has a good text-index, than that person can turn on the SPARQL-based autocompletion

**Comment by LaurensRietveld** [comment]
No plans here on building this into Yasqe as SPARQL endpoints often aren't good at answering these kind of queries. Instead, focussing on other means of autocompletion (see e.g. autocompletion here https://triplydb.com/wikimedia/dbpedia/sparql/dbpedia).
Still, whenever somebody is interested in this anyway, building such an autocompletion plugin for yasqe should be straightforward (see https://triply.cc/docs/yasgui-api#yasqe for getting a headstart, and https://github.com/TriplyDB/Yasgui/tree/master/packages/yasqe/src/autocompleters for example implementations)
