### ISSUE TITLE
Query error on count distinct

### ISSUE THREAD

**Issue by zorino** [Triply-Dev/YASGUI.YASQE-deprecated#82]
![image](https://cloud.githubusercontent.com/assets/1028795/15515976/6ed96ce2-21a5-11e6-9e32-f4b32d59d03a.png)

SELECT COUNT DISTINCT ?X 
should be valid

**Comment by LaurensRietveld** [comment]
Are you sure? This is not valid according to the SPARQL spec: https://www.w3.org/TR/sparql11-query/#rSelectClause
Endpoints such as virtuoso are a bit more flexible though, and deviated from the SPARQL spec

**Comment by LaurensRietveld** [comment]
fyi, the valid version of your query

```
SELECT (COUNT(DISTINCT ?variable) as ?c) WHERE {
 ?variable ?pred ?obj   
}
```

**Comment by zorino** [comment]
sorry about that you're right, I should've checked the sparql spec first, 
thank you
