### ISSUE TITLE
createCurlString doesn't work if queries are sent via the GET method

### ISSUE THREAD

**Issue by jindrichmynarz** [Triply-Dev/YASGUI.YASQE-deprecated#84]
`createCurlString` method doesn't work if queries are sent via the GET method because it expects the `data` attribute of `ajaxConfig` to be available (see [here](https://github.com/OpenTriply/YASGUI.YASQE/blob/gh-pages/src/curl.js#L12)). However, `data` is set only if the `yasqe.options.sparql.requestMethod` is not `GET` (see [here](https://github.com/OpenTriply/YASGUI.YASQE/blob/gh-pages/src/sparql.js#L44-L54)). If the request method is `GET`, YASQE does its own encoding of the query params into the endpoint's URL (see #78 and [here](https://github.com/OpenTriply/YASGUI.YASQE/blob/gh-pages/src/sparql.js#L44-L51)), so `data` is not provided.

**Comment by LaurensRietveld** [comment]
A thorough bug report, thanks, I'll take a look

**Comment by LaurensRietveld** [comment]
I've fixed this issue (together with another CURL related bug #86 ). Released as version 2.10.1
