### ISSUE TITLE
Infinite loop when commenting first prefix

### ISSUE THREAD

**Issue by LaurensRietveld** [Triply-Dev/YASGUI.YASQE-deprecated#87]
Problem is somewhere in the `findFirstPrefix` function

**Comment by simonlmartin** [comment]
This issue returned with commit:

https://github.com/OpenTriply/YASGUI.YASQE/commit/5a547b6e67c3de62f7d77516235df2dba5fc8a7b#diff-7e7da92b0ce308817700b10ad6f7edd3
