### ISSUE TITLE
Uncaught TypeError: child.getAllWords is not a function

### ISSUE THREAD

**Issue by masda70** [Triply-Dev/YASGUI.YASQE-deprecated#95]
When using YASQE in an environment where the Array object has been extended (in my case this is done by Ember.js, which I use), the prefix autocompleter causes the following error to be thrown:

```
Uncaught TypeError: child.getAllWords is not a function 
  at module.exports.getAllWords (trie.js:235)
  [...]
```

This happens for instance when writing `rdfs:` in the editor and expecting YASQE to add the corresponding prefix to the current query. It chokes when hitting the ROOT() of the Trie.

One solution that worked in my case is to perform a safer iteration of T.children properties in the getAllWords function using the standard `hasOwnProperty` check:
```
      for(k in T.children) {
        if (T.children.hasOwnProperty(k)){
          child = T.children[k];
          ret = ret.concat(child.getAllWords(str + k));
        }
      }
```

**Comment by LaurensRietveld** [comment]
thanks for the report, this should be fixed now in the newest version
