### ISSUE TITLE
Infinite loop when pasting a query in quotes 

### ISSUE THREAD

**Issue by elated** [Triply-Dev/YASGUI.YASQE-deprecated#96]
Browser hangs because of infinite loop in findFirstPrefix function when pasting the following line in the editor:

"PREFIX dc: \nDELETE DATA\n{\nGRAPH {\n dc:title \"A new book\" ;\n dc:creator \"A.N.Other\" .\n }\n}"
Paste with the quotes.

**Comment by LaurensRietveld** [comment]
thanks for the report, this should be fixed in the newest version
