### ISSUE TITLE
Improve indentation

### ISSUE THREAD

**Issue by wouterbeek** [Triply-Dev/YASGUI.YASQE-deprecated#98]
Indentation is sometimes a bit unpredictable / illogical.  I will illustrate this with some concrete cases.

Pressing ENTER after a `WHERE` clause indents 4 spaces, but we are outside of any for of nesting, so I was expecting indentation to be zero here:

```sparql
select * {
  :s [:p :o ]
}
    *HERE*
```

Pressing ENTER at the position marked `*HERE*` changes the indentation of that line (it moves to the left):

```sparql
select * {
  :a :b [
    :c [
      :d :e*HERE*
```

**Comment by LaurensRietveld** [comment]
closed. your second use case is covered, your first one isnt (as that isnt a valid sparql query)
